# Generated by Django 4.2.3 on 2023-07-03 15:15
import autoslug.fields

import autoslug.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=django.utils.timezone.now, editable=False, populate_from="user"
            ),
            preserve_default=False,
        ),
    ]
