# Generated by Django 4.2.3 on 2023-07-03 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_profile_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="user",
            new_name="username",
        ),
    ]
