# Generated by Django 4.2.3 on 2023-07-03 15:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_rename_user_profile_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="username",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="slug",
        ),
    ]
